=== nicosteiner/SiteCheckr/data/rulesets/ruleset.dtd
<!ELEMENT ruleset (title,description?,author?,version?,rules)>

<!ATTLIST ruleset
    version CDATA "1.0">
    
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT version (#PCDATA)>

<!ELEMENT rules (rule|stdrule)*>

<!ELEMENT rule (title, description?, tests)>
<!ELEMENT stdrule (title, description?)>

<!ELEMENT tests (test*)>
<!ELEMENT test (#PCDATA)>

<!ENTITY % PRIORITY
  "(required|nicetohave)"
   >

<!ATTLIST rule
    priority %PRIORITY; "required">

<!ATTLIST stdrule
    id ID #REQUIRED
    priority %PRIORITY; "required">
     
<!ENTITY % MODE
  "(required|forbidden)"
   >

<!ENTITY % TYPE
  "(xpath|css)"
   >
         
<!ATTLIST test
    type %TYPE; "xpath"
    mode %MODE; "required">

=== nicosteiner/SiteCheckr/data/rulesets/en-sample-ruleset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleset SYSTEM "ruleset.dtd">
<ruleset>
    <title>Sample Ruleset</title>
    <description>This ruleset shows how to write rules for the addon.</description>
    <author>info@sitecheckr.de</author>
    <rules>

        <rule>
            <title>HTML structure</title>
            <description>Document has to be composed of html, head (with title) and body.</description>
            <tests>
                <test>count(/html)=1</test>
                <test>count(/html/head)=1</test>
                <test>count(/html/head/title)=1</test>
                <test>count(/html/body)=1</test>
            </tests>
        </rule>

        <rule>
            <title>Deprecated Tags</title>
            <description>u-, s-, center-, font- and strike-tags are deprecated.</description>
            <tests>
                <test mode="forbidden">//u</test>
                <test mode="forbidden">//s</test>
                <test mode="forbidden">//center</test>
                <test mode="forbidden">//font</test>
                <test mode="forbidden">//strike</test>
            </tests>
        </rule>

        <rule>
            <title>Alternative text for images</title>
            <description>All images need some alternative text.</description>
            <tests>
                <test mode="forbidden">//img[not(@alt)]</test>
            </tests>
        </rule>

    </rules>
</ruleset>

=== nicosteiner/SiteCheckr/data/rulesets/de-sample-ruleset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleset SYSTEM "ruleset.dtd">
<ruleset>
    <title>Beispiel Regelsatz</title>
    <description>Dieser Regelsatz zeigt, wie man Regeln für das Addon schreibt.</description>
    <author>info@sitecheckr.de</author>
    <rules>

        <rule>
            <title>HTML-Grundgerüst</title>
            <description>Überprüft, dass ein standard-konformes HTML-Grundgerüst (html, head, title, body) vorhanden ist.</description>
            <tests>
                <test>count(/html)=1</test>
                <test>count(/html/head)=1</test>
                <test>count(/html/head/title)=1</test>
                <test>count(/html/body)=1</test>
            </tests>
        </rule>
        <rule>
            <title>Deprecated Tags</title>
            <description>u-, s-, center-, font- und strike-Tags sollten nicht mehr verwendet werden.</description>
            <tests>
                <test mode="forbidden">//u</test>
                <test mode="forbidden">//s</test>
                <test mode="forbidden">//center</test>
                <test mode="forbidden">//font</test>
                <test mode="forbidden">//strike</test>
            </tests>
        </rule>
        <rule>
            <title>Alternativ-Text für Bilder</title>
            <description>Alle Bilder müssen einen Alternativ-Text haben.</description>
            <tests>
                <test mode="forbidden">//img[not(@alt)]</test>
            </tests>
        </rule>

    </rules>
</ruleset>

=== nicosteiner/SiteCheckr/data/rulesets/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleset SYSTEM "ruleset.dtd">
<ruleset>
    <title>Demo-Ruleset</title>
    <description>This ruleset shows how to write rules for the addon.</description>
    <author>info@sitecheckr.de</author>
    <version>1.2</version>
    
    <rules>
          
      <rule>
          <title>alt-text for images</title>
          <description><![CDATA[All img-tags need an alt-attribute.]]></description>
          <tests>
            <test mode="forbidden">//img[not(@alt)]</test>
          </tests>
      </rule>
    
      <!-- <rule>
          <title>type-attribute for style- and script-tags</title>
          <description><![CDATA[All <code>style</code>- and <code>script</code>-tags need a <code>type</code>-attribute.]]></description>
          <tests>
            <test mode="forbidden">//style[not(@type)]</test>
            <test mode="forbidden">//script[not(@type)]</test>
          </tests>
      </rule>  -->
      <stdrule id="duplicateId">
          <title>Every ID has to be unique</title>
      </stdrule>
        
      <rule priority="nicetohave">
          <title>Inline Styles</title>
          <description><![CDATA[You should avoid inline styles]]></description>
          <tests>
            <test mode="forbidden"><![CDATA[//*[@style]]]></test>
          </tests>
      </rule>
      
      <rule>
          <title><![CDATA[title Tag]]></title>
          <description><![CDATA[The document should have a title-tag]]></description>
          <tests>
            <test><![CDATA[count(//html/head/title)=1]]></test>
          </tests>
      </rule>

      <rule>
          <title>Deprecated Tags</title>
          <description><![CDATA[Tags like u, s, center, font or strike should be avoided.]]></description>
          <tests>
            <test mode="forbidden"><![CDATA[//u]]></test>
            <test mode="forbidden"><![CDATA[//s]]></test>
            <test mode="forbidden"><![CDATA[//center]]></test>
            <test mode="forbidden"><![CDATA[//font]]></test>
            <test mode="forbidden"><![CDATA[//strike]]></test>
          </tests>
      </rule>
       
      <rule priority="nicetohave">
          <title>Semantic Tags</title>
          <description><![CDATA[Tags like b or i should be avoided. Consider using strong or em]]></description>
          <tests>
            <test mode="forbidden"><![CDATA[//b]]></test>
            <test mode="forbidden"><![CDATA[//i]]></test>
          </tests>
      </rule>
    </rules>
</ruleset>

=== nicosteiner/SiteCheckr/data/rulesets/de-seo-ruleset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleset SYSTEM "ruleset.dtd">
<ruleset>
    <title>Suchmaschinenoptimierung - Basics</title>
    <description>Überprüft grundlegende SEO-Anforderungen.</description>
    <author>info@sitecheckr.de</author>
    <rules>

        <rule>
            <title>Korrekter title-Tag vorhanden</title>
            <description>Jede Website muss einen title besitzen. Dieser sollte max. 65 Zeichen lang sein.</description>
            <tests>
                <test>count(/html/head/title)=1</test>
                <test>string-length(/html/head/title)>0</test>
                <test>string-length(/html/head/title)&lt;=65</test>
            </tests>
        </rule>
        <rule>
            <title>Korrekte Meta-Description vorhanden</title>
            <description>Es sollte eine Meta-Description mit max. 150 Zeichen Länge vorhanden sein.</description>
            <tests>
                <test>count(/html/head/meta[@name="description"])=1</test>
                <test>string-length(/html/head/meta[@name="description"]/@content)>0</test>
                <test>string-length(/html/head/meta[@name="description"]/@content)&lt;=150</test>
            </tests>
        </rule>
        <rule>
            <title>Alternativ-Text für Bilder</title>
            <description>Alle Bilder müssen einen Alternativ-Text haben.</description>
            <tests>
                <test mode="forbidden">//img[not(@alt)]</test>
            </tests>
        </rule>
        <rule priority="nicetohave">
            <title>Links sollten ein title-Attribut haben</title>
            <description></description>
            <tests>
                <test mode="forbidden">//a[@href and not(@title)]</test>
            </tests>
        </rule>
    </rules>
</ruleset>
